name: build
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: |
          cp .env.example .env
          ./vessel start
          ./vessel composer install
          ./vessel artisan migrate
          ./vessel npm install
          ./vessel npm run dev
      - name: Run the tests
        run: |
          ./vessel artisan test